version: '3.1'

services:
  db:
    image: postgres
    restart: always
    volumes:
      - ./db/postgresql:/var/lib/postgresql
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '5432:5432'
  redis:
    image: redis
    restart: always
    ports:
      - '6379:6379'
  nats:
    image: nats
    restart: always
    ports:
      - '4444:4444'
